server:
  port: 9080
spring:
    freemarker:
        template-loader-path: classpath:/templates/
        check-template-location: false

    datasource:
        url: jdbc:mysql://localhost:3306/magic2?useSSL=false&characterEncoding=utf8
        username: root
        password: iyuyun
        filters: stat
        maxActive: 20
        initialSize: 10
        maxWait: 20
        minIdle: 1
        maxIdle: 10
        timeBetweenEvictionRunsMillis: 3600000
        minEvictableIdleTimeMillis: 18000000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    jpa:
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate.format_sql: true
            hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            hibernate.cache.use_second_level_cache: false
            hibernate.search.default.directory_provider: filesystem
            hibernate.search.default.indexBase: ./indexes
        open-in-view: true